

GET http://localhost:8080/books
Content-Type: application/json

# POST http://localhost:8080/books
# Content-Type: application/json

# {
#     "Title" : "Verity",
#     "Author" : "Collen Rover",
#     "Category" : "Suspense",
#     "Synopsis" : "Nem tudo que achamos realmente é"
# }

PUT http://localhost:8080/books/4
Content-Type: application/json

{
    "Synopsis" : "Sinopse de teste"
}

# DELETE http://localhost:8080/books/2
# Content-Type: application/json